// ツール名 → 日本語ラベルの対応表
// agentRunner（進捗表示）と AITracePanel（履歴表示）の両方で使用する

export const TOOL_LABELS: Record<string, string> = {
  findPersons:                     '従業員検索',
  findOrgs:                        '組織検索',
  getPersonsDetail:                '従業員詳細取得',
  getReviewSummary:                '変更サマリー確認',
  getOrgTree:                      '組織図表示',
  getChangedRows:                  '変更行一覧',
  getValidationIssues:             'バリデーション問題一覧',
  findVacantPositions:             '空席ポジション検索',
  getValidationDiagnosis:          'バリデーション確認',
  getFieldOptions:                 '入力可能値確認',
  undo:                            '操作取り消し',
  show_org_members:                '組織メンバー表示',
  propose_bulk_transfer:           '一括異動',
  propose_field_edit:              'フィールド変更',
  propose_bulk_set_field:          '一括設定',
  propose_transfer:                '異動',
  propose_promotion:               '昇格',
  propose_create_position:         '空席ポジション作成',
  propose_assign_person:           '配属',
  propose_change_position:         'ポジション変更',
  propose_set_manager_position:    '上司ポジション設定',
  propose_re_derive_manager_names: '上司名再導出',
  getUnassignedPositions:          '未割当ポジション確認',
  propose_assign_position_codes:   'ポジションコード割り当て',
  propose_re_derive_org_sub_fields:'組織サブフィールド再導出',
  propose_mark_absent:              '4/1不在登録',
  propose_leave_of_absence:        '休職',
  propose_return_from_leave:       '復職',
  propose_concurrent_add:          '兼務追加',
  propose_concurrent_release:      '兼務解除',
  propose_secondment_to_concurrent:'本務出向→兼務出向変換',
  propose_secondment_transfer:     '出向先転籍',
  propose_demotion:                '降格',
  propose_org_restructure:         '組織コード変更',
  propose_job_type_change:         '職種変更',
  ui_open_operation:               'フォームを開く',
  ui_get_form_state:               'フォーム状態確認',
  ui_suggest_form_field:           'フォーム値を設定',
  ui_show_person:                  '画面フォーカス',
  ui_focus_row:                    '画面フォーカス',
}
