import type { FieldDef } from '../types'

// Array order = CSV column order.
// key   = JS property name (used in schema / resolver)
// header = SF CSV row-1 header (omitted when identical to key)
export const JOB_CLASSIFICATION_IMPORT_FIELDS: FieldDef[] = [
  { key: 'userId',               header: 'user-id',               en: 'User ID',                        ja: 'ユーザーID' },
  { key: 'startDate',            header: 'start-date',            en: 'Event Date',                     ja: 'イベント日付' },
  { key: 'seqNumber',            header: 'seq-number',            en: 'seq-number',                     ja: 'seq-number' },
  { key: 'eventReason',          header: 'event-reason',          en: 'event-reason',                   ja: 'event-reason' },
  { key: 'expectedReturnDate',   header: 'expected-return-date',  en: 'Expected Return Date',           ja: '復職予定日' },
  { key: 'position',                                              en: 'Position',                       ja: 'ポジション' },
  { key: 'positionEntryDate',                                     en: 'Position Entry Date',            ja: 'ポジション配属日' },
  { key: 'company',                                               en: 'Legal Entity',                   ja: '会社' },
  { key: 'businessUnit',         header: 'business-unit',         en: 'Business Unit',                  ja: 'ビジネスユニット' },
  { key: 'division',                                              en: 'Division',                       ja: '部門/会社' },
  { key: 'department',                                            en: 'Department',                     ja: '組織' },
  { key: 'location',                                              en: 'Location',                       ja: '勤務場所' },
  { key: 'costCenter',           header: 'cost-center',           en: 'Cost Center',                    ja: 'コストセンター' },
  { key: 'timezone',                                              en: 'Timezone',                       ja: 'タイムゾーン' },
  { key: 'concurrentType',       header: 'custom-string29',       en: 'Concurrent Type',                ja: '兼務区分' },
  { key: 'employeeClass',        header: 'employee-class',        en: 'Employee Class',                 ja: '社員クラス' },
  { key: 'employmentType',       header: 'employment-type',       en: 'Employment Type',                ja: '雇用タイプ' },
  { key: 'contractEndDate',      header: 'contract-end-date',     en: 'Contract End Date',              ja: '契約終了日' },
  { key: 'ccVacationEndDate',    header: 'custom-date7',          en: 'CC Vacation End Date',           ja: '能力開発休暇終了予定日' },
  { key: 'managerId',            header: 'manager-id',            en: 'Supervisor',                     ja: '上司' },
  { key: 'jobCode',              header: 'job-code',              en: 'Job Classification',             ja: 'ジョブタイトル' },
  { key: 'jobTitle',             header: 'job-title',             en: 'Global Job Title',               ja: '職務名称' },
  { key: 'jobFamily',            header: 'custom-string31',       en: 'Job Family',                     ja: 'ジョブファミリー（職種）' },
  { key: 'jobType',              header: 'custom-string30',       en: 'Job Type',                       ja: 'ジョブタイプ（職務）' },
  { key: 'officialPositionCode', header: 'custom-string12',       en: 'Official Position Code',         ja: '役職' },
  { key: 'localJobTitle',        header: 'local-job-title',       en: 'Local Job Title',                ja: 'フリータイトル' },
  { key: 'jobLevel',             header: 'custom-string13',       en: 'Job Level',                      ja: 'ジョブ（職務）レベル' },
  { key: 'jobLevelPosition',     header: 'custom-string33',       en: 'Job Level(Position)',            ja: 'ジョブ（職務）レベル（ポジション）' },
  { key: 'payGrade',             header: 'pay-grade',             en: 'Pay Grade',                      ja: '給与等級' },
  { key: 'dateOfCurrentPayGrade', header: 'custom-date6',         en: 'Date of Current Pay Grade',      ja: '現給与等級開始日' },
  { key: 'unionFlag',            header: 'custom-string18',       en: 'Union Flag',                     ja: '労働組合員サイン' },
  { key: 'unionCode',            header: 'custom-string19',       en: 'Union Code',                     ja: '労組管理コード' },
  { key: 'gvWorkFlag',           header: 'custom-string26',       en: 'G/V-Work Flag',                  ja: '裁量労働対象' },
  { key: 'fte',                                                   en: 'FTE',                            ja: 'FTE' },
  { key: 'standardHours',        header: 'standard-hours',        en: 'Standard Weekly Hours',          ja: '標準週労働時間' },
  { key: 'shiftCode',            header: 'shift-code',            en: 'Shift Code',                     ja: '給食理由（詳細）' },
  { key: 'detailedReasonForLoa', header: 'custom-string20',       en: 'Detailed Reason for LOA',        ja: '私傷病休職時の病名' },
  { key: 'sickNameForLoa',       header: 'custom-string24',       en: 'Sick Name for LOA',              ja: '出向受入社員の出向元会社社員番号' },
  { key: 'entryIntoGroup',       header: 'custom-date1',          en: 'Entry into Group',               ja: '出向受入社員の出向元会社入社年月日' },
  { key: 'corporation',          header: 'custom-string25',       en: 'Corporation',                    ja: '出向受入社員の出向元会社' },
  { key: 'jobEntryDate',                                          en: 'Job Entry Date',                 ja: '職務配属日' },
  { key: 'companyEntryDate',                                      en: 'Company Entry Date',             ja: '会社配属日' },
  { key: 'locationEntryDate',                                     en: 'Location Entry Date',            ja: '勤務場所配属日' },
  { key: 'departmentEntryDate',                                   en: 'Department Entry Date',          ja: '部署配属日' },
  { key: 'hireDate',                                              en: 'Hire Date',                      ja: '入社日' },
  { key: 'originalStartDate',    header: 'custom-date2',          en: 'Original Start Date',            ja: '最初の入社日' },
  { key: 'seniorityStartDate',   header: 'custom-date3',          en: 'Seniority Start Date',           ja: '勤続期間起算日' },
  { key: 'firstDateWorked',      header: 'custom-date4',          en: 'First Date Worked',              ja: '入社年月日（年休計算）' },
  { key: 'hireType',             header: 'custom-string22',       en: 'Hire Type',                      ja: '採用区分コード' },
  { key: 'hireTypeDetail',       header: 'custom-string23',       en: 'Hire Type(Detail)',              ja: '採用識別コード' },
  { key: 'localEmployeeNumber',  header: 'custom-string27',       en: 'Local Employee Number',          ja: '社員番号（個社）' },
  { key: 'masterEmpKey',         header: 'custom-string28',       en: 'MasterEmpKey',                   ja: '従業員識別キー' },
  { key: 'timeTypeProfileCode',  header: 'time-type-profile-code', en: 'Time Profile',                  ja: '時間プロファイル' },
  { key: 'holidayCalendarCode',  header: 'holiday-calendar-code', en: 'Holiday Calendar',               ja: '祝日カレンダー' },
  { key: 'workscheduleCode',     header: 'workschedule-code',     en: 'Work Schedule',                  ja: '勤務スケジュール' },
  { key: 'operation',                                             en: 'Operation',                      ja: '' },
]

export const JOB_CLASSIFICATION_IMPORT_LABEL_MAP: Record<string, Omit<FieldDef, 'key'>> = Object.fromEntries(
  JOB_CLASSIFICATION_IMPORT_FIELDS.map(f => [f.key, { header: f.header, en: f.en, ja: f.ja }])
)
