import type { FieldDef } from '../types'

// Array order = CSV column order.
export const POSITION_IMPORT_FIELDS: FieldDef[] = [
  { key: '[OPERATOR]',                             en: 'Supported operators: Delimit, Clear and Delete', ja: 'サポートされる操作:' },
  { key: 'code',                                   en: '', ja: '' },
  { key: 'changeReason.externalCode',              en: '', ja: '' },
  { key: 'cust_jobFamily.externalCode',            en: '', ja: '' },
  { key: 'cust_jobFunction.externalCode',          en: '', ja: '' },
  { key: 'company.externalCode',                   en: '', ja: '' },
  { key: 'businessUnit.externalCode',              en: '', ja: '' },
  { key: 'division.externalCode',                  en: '', ja: '' },
  { key: 'department.externalCode',                en: '', ja: '' },
  { key: 'cust_solution.externalCode',             en: 'Picklist Value.External Code', ja: 'ピックリストの値.外部コード' },
  { key: 'cust_ShukkoHakenFlag.externalCode',      en: '', ja: '' },
  { key: 'cust_SecondedCompany.externalCode',      en: '', ja: '' },
  { key: 'cust_officialPositionCode.externalCode', en: '', ja: '' },
  { key: 'externalName.en_US',                     en: '', ja: '' },
  { key: 'externalName.defaultValue',              en: '', ja: '' },
  { key: 'externalName.ja_JP',                     en: '', ja: '' },
  { key: 'location.externalCode',                  en: '', ja: '' },
  { key: 'costCenter.externalCode',                en: '', ja: '' },
  { key: 'jobCode.externalCode',                   en: '', ja: '' },
  { key: 'description',                            en: '', ja: '' },
  { key: 'effectiveStartDate',                     en: '', ja: '' },
  { key: 'cust_ExpectedFulfillmentDate',           en: '', ja: '' },
  { key: 'jobLevel.externalCode',                  en: '', ja: '' },
  { key: 'effectiveStatus',                        en: '', ja: '' },
  { key: 'cust_scheduledEndDate',                  en: '', ja: '' },
  { key: 'payGrade.externalCode',                  en: '', ja: '' },
  { key: 'payRange.externalCode',                  en: '', ja: '' },
  { key: 'cust_min',                               en: '', ja: '' },
  { key: 'cust_mid',                               en: '', ja: '' },
  { key: 'cust_max',                               en: '', ja: '' },
  { key: 'vacant',                                 en: '', ja: '' },
  { key: 'cust_assignType.externalCode',           en: '', ja: '' },
  { key: 'employeeClass.externalCode',             en: '', ja: '' },
  { key: 'cust_employmentType.externalCode',       en: '', ja: '' },
  { key: 'standardHours',                          en: '', ja: '' },
  { key: 'targetFTE',                              en: '', ja: '' },
  { key: 'multipleIncumbentsAllowed',              en: '', ja: '' },
  { key: 'type.code',                              en: '', ja: '' },
  { key: 'positionControlled',                     en: '', ja: '' },
  { key: 'cust_TrainingAssignmentFlag',            en: '', ja: '' },
  { key: 'cust_LaborUnionFull_timeAssignmentFlag', en: '', ja: '' },
  { key: 'cust_UnionFlag.externalCode',            en: '', ja: '' },
  { key: 'cust_V_WorkFlag',                        en: '', ja: '' },
  { key: 'cust_PositionCreateReason.externalCode', en: '', ja: '' },
  { key: 'parentPosition.code',                    en: '', ja: '' },
  { key: 'technicalParameters',                    en: '', ja: '' },
]

export const POSITION_IMPORT_LABEL_MAP: Record<string, Omit<FieldDef, 'key'>> = Object.fromEntries(
  POSITION_IMPORT_FIELDS.map(f => [f.key, { en: f.en, ja: f.ja }])
)
